### ISSUE TITLE
Error parsing JS that contains property lookup `macro`

### ISSUE THREAD

**Issue by BinaryMuse** [mozilla/sweet.js#292]
Similar to #289, I ran into a failure that can be reproduced with this case:

```javascript
it("works when 'macro' is a property lookup", function() {
  var obj = {
    macro: 42
  };

  expect(obj.macro).to.eql(42);
});
```

When parsing `obj.marco` in the last line, it throws a stack trace like this:

```
/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/sweet.js:101
                    throw err;
                          ^
TypeError: Cannot call method 'expose' of undefined
    at eval (eval at <anonymous> (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:19:39)
    at step (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1207:30)
    at enforest (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1334:16)
    at step (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1136:38)
    at step (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1128:28)
    at step (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1143:28)
    at step (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1294:28)
    at enforest (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1334:16)
    at expandToTermTree (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1506:17)
    at expandTermTreeToFinal (/Users/btilley/.nvm/v0.10.26/lib/node_modules/sweet.js/lib/expander.js:1735:34)
```

I've been trying to track the cause of this one down, but it's giving me a bit more trouble than the last one. :)

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
