### ISSUE TITLE
emoji macros don't work

### ISSUE THREAD

**Issue by jlongster** [mozilla/sweet.js#329]
I bet this is a simple fix somewhere in whatever reads the file in. This doesn't work:

```
macro 😻  {
  rule { $x } => { $x + 5 }
}

function distance() {
  var foo = 😻 6;
  return foo;
}
```

While this does:

```
macro < {
  rule { $x } => { $x + 5 }
}

function distance() {
  var foo = < 6;
  return foo;
}
```

EDIT: here's the error:

```
/usr/local/lib/node_modules/sweet.js/lib/parser.js:1898
        throw error;
              ^
Error: Line 2: Unexpected token ILLEGAL
[... ) } )  ...]
    at throwError (/usr/local/lib/node_modules/sweet.js/lib/parser.js:1892:21)
    at scanPunctuator (/usr/local/lib/node_modules/sweet.js/lib/parser.js:802:9)
    at advance (/usr/local/lib/node_modules/sweet.js/lib/parser.js:1396:16)
    at _advance (/usr/local/lib/node_modules/sweet.js/lib/parser.js:4727:35)
    at readToken (/usr/local/lib/node_modules/sweet.js/lib/parser.js:4797:16)

```

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
