### ISSUE TITLE
Error with infix rule

### ISSUE THREAD

**Issue by r3m0t** [mozilla/sweet.js#402]
```
macro @ {
    rule infix { $val:expr | _ $x (.) ... } => { $val }
}
log(a@b.b);
```

Gives error:
```
/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:5213
            throw e;
                  ^
Error: Line 4: Unexpected identifier
[... a ) b ) ;  ...]
    at throwError (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:1887:21)
    at throwUnexpected (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:1923:13)
    at expect (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:1946:13)
    at parseArguments (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:2310:17)
    at trackLeftHandSideExpressionAllowCall (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:4230:24)
    at parsePostfixExpression (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:2381:20)
    at /home/tomer/tmp/node_modules/sweet.js/lib/parser.js:4316:38
    at parseUnaryExpression (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:2402:20)
    at /home/tomer/tmp/node_modules/sweet.js/lib/parser.js:4316:38
    at parseBinaryExpression (/home/tomer/tmp/node_modules/sweet.js/lib/parser.js:2499:16)
```

Whereas this:
```
macro @ {
    rule infix { $val:expr | _ $x:ident (.) ... } => { $val }
}
log(a@b.b);
```

Gives output `log(a.b);` instead of the expected `log(a);`

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
