### ISSUE TITLE
TypeError for Missing Open Bracket of Rule Output

### ISSUE THREAD

**Issue by Havvy** [mozilla/sweet.js#407]
```javascript
macro baderror {
	rule { () } =>
	// {
	}
}
```

I'd expect to get this error:

```
Error: Line 4: Unexpected token }
[... } } ...]
```

Instead, we get a type error "Cannot read property 'token' of undefined", which is not helpful.

```
/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/sweet.js:101
                    throw err;
                          ^
TypeError: Cannot read property 'token' of undefined
    at eval (eval at <anonymous> (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/scopedEval.js:16:69), <anonymous>:79:59)
    at expandMacro (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:1223:18)
    at step (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:1613:30)
    at enforest (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:1751:16)
    at expandToTermTree (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:2009:17)
    at expandTermTreeToFinal (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:2285:34)
    at /home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:2357:24
    at Array.map (native)
    at Function._.map._.collect (/home/havvy/sweetjs/playground/node_modules/sweet.js/node_modules/underscore/underscore.js:95:56)
    at expand (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/expander.js:2356:23)
```

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
