### ISSUE TITLE
Confusing Error When Adding Comma Between Rules

### ISSUE THREAD

**Issue by Havvy** [mozilla/sweet.js#408]
```javascript
macro commaBetweenRules {
    rule { a } => { "a" },
    rule { b } => { "b" }
}
```

I'd expect an error similar to the following:

```
SyntaxError on Line 2 of theFile.sjs: Macro rules should not be separated by commas.
```

Instead, I get something about syntax objects and delimiters:

```
/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/sweet.js:99
                    throw new SyntaxError(syn.printSyntaxError(source$2, err))
                          ^
SyntaxError: [mkSyntax] Must provide inner array of syntax objects when creating a delimiter
    at expand$2 (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/sweet.js:99:27)
    at parse (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/sweet.js:135:29)
    at Object.compile (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/sweet.js:143:19)
    at Object.exports.run (/home/havvy/sweetjs/playground/node_modules/sweet.js/lib/sjs.js:85:27)
    at Object.<anonymous> (/home/havvy/sweetjs/playground/node_modules/sweet.js/bin/sjs:7:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
