### ISSUE TITLE
Binary debugging utility

### ISSUE THREAD

**Issue by kristianmandrup** [mozilla/sweet.js#417]
I propose the following binary which wraps your debug.js proposal ;)
https://github.com/mozilla/sweet.js/blob/master/debug.js

https://github.com/kristianmandrup/sweet.js/blob/es6-modules/bin/sjs-debug

```js
#!/usr/bin/env node-debug

var parser = require("../build/lib/parser");
var expander = require("../build/lib/expander");
var patterns = require("../build/lib/patterns");
var sweet = require("../build/lib/sweet");
var codegen = require("escodegen");

var fs = require("fs");

var program = require('commander');

program
  .version('0.0.1')
  .usage('<files>')

  .on('--help', function(){
    console.log('requires that you have built sweet.js');
    console.log('in the console/terminal run: grunt');
    console.log('which will build the files (will create a /build folder)');
    console.log('Then you can run: sjs-debug <files ...>');
    console.log('Enjoy :)');
  })
  .parse(process.argv);

var files = program.args;

files.forEach(function(file) {
  compileMacro(file);
})

function compileMacro(file) {
  var filePath = "./" + file;
  var source = fs.readFileSync(filePath, "utf8");

  var result = sweet.compile(source, {filename: filePath});

  console.log(codegen.generate(parser.parse(result)));
}
```

However when I run it:

`bin/sjs-debug test.js`

```js
// test.js

#lang "./macros/stxcase.js";
import { id } from "./mod.js";
id(42);
```

It opens up my browser at http://localhost:8080/debug?port=5858 and stops at

line 456 in `module.js`  `return compiledWrapper.apply(self.exports, args);` and when I click play...

```bash
$ bin/sjs-debug test.js
Node Inspector is now available from http://localhost:8080/debug?port=5858
Debugging `bin/sjs-debug`

debugger listening on port 5858

/Users/kristianmandrup/experiments/macros/sweet.js/build/lib/parser.js:4882
            throw e;
                  ^
TypeError: Cannot read property 'range' of undefined
    at peek (/Users/kristianmandrup/experiments/macros/sweet.js/build/lib/parser.js:1391:26)
    at parseProgram (/Users/kristianmandrup/experiments/macros/sweet.js/build/lib/parser.js:3910:9)
    at Object.parse (/Users/kristianmandrup/experiments/macros/sweet.js/build/lib/parser.js:4870:23)
    at compileMacro (/Users/kristianmandrup/experiments/macros/sweet.js/bin/sjs-debug:38:39)
    at filePath (/Users/kristianmandrup/experiments/macros/sweet.js/bin/sjs-debug:29:3)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/kristianmandrup/experiments/macros/sweet.js/bin/sjs-debug:28:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

How is this supposed to help me debug? What am I doing wrong here if anything?

Any ideas?

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
