### ISSUE TITLE
Translate a RegExp into SweetJS

### ISSUE THREAD

**Issue by IngwiePhoenix** [mozilla/sweet.js#471]
Out of curiosity, I had written a RegExp function that would translate any occurence of an ObjC style block into a proper anymous function.

```javascript
^{ console.log("Foo"); }
// becomes
function(){ console.log("Foo"); } // I thought about adding: .bind(this)

^(arg){ console.log(arg); }
// ->
function(arg){ console.log(arg); }

// A practical use:
app.use("/", ^(reg, res){
    res.send("o.o");
});
```

The code I wrote to make this translation:

```javascript
var blockRegexp = /\^(\(.*?\))?({[\s\S]*?})/g;
module.exports = function(src) {
    var res = src.replace(blockRegexp, function(block, args, body, index, match){
        return "function"
            +(typeof args == "undefined" ? "()" : args)
            +body;
    });
    return res;
}
```

My use-case is in combination with [OJ](https://github.com/musictheory/oj), where I could realize a very ObjC like extension.

How would I go about translating my little RegExp hackery into a SweetJS macro?

**Comment by natefaubion** [comment]
This is something sweet.js excels at :).

```js
// Non-recursive macro so we can fallback to the ^ operator
// when we don't have a match
let (^) = macro {
    rule { ($args:ident (,) ...) { $body ... } } => {
        function ($args (,) ...) { $body ... }
    }
    rule { { $body ... } } => {
        function () { $body ... }
    }
    // Fallback to operator usage
    rule { } => { ^ }
}

foo.bar(^{
    return 42
})

foo.baz(^(err, res){
    console.log(res)
})

var foo = 4 ^ 2
```
```js
foo.bar(function () {
    return 42;
});
foo.baz(function (err, res) {
    console.log(res);
});
var foo = 4 ^ 2;
```

**Comment by IngwiePhoenix** [comment]
This. is. awesome. Where can I learn how to do magic like this? ;)

Very nice. I am going to test this if it will run nicely within OJ. Thanks for the macro, will let you know if it worked and close the issue then. :)

**Comment by natefaubion** [comment]
I would start with the docs http://sweetjs.org/doc/main/sweet.html

**Comment by IngwiePhoenix** [comment]
Awh. The parser does not like ObjC.

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/sjs-test $ cat t.sjs 
let (^) = macro {
    rule { ($args:ident (,) ...) { $body ... } } => {
        function ($args (,) ...) { $body ... }
    }
    rule { { $body ... } } => {
        function () { $body ... }
    }
    // Fallback to operator usage
    rule { } => { ^ }
}

@implementation Foo
+(id)barMyCb:(callable)cb {
    cb();
}
@end

[Foo barMyCb:^{ console.log("o3o"); }];
Ingwie@Ingwies-Macbook-Pro.local ~/W/sjs-test $ sjs -r ./t.sjs 
/usr/local/lib/node_modules/sweet.js/lib/parser.js:4876
            throw e;
                  ^
Error: Line 12: Unexpected token @
[... @ implementation Foo + ...]
    at throwError (/usr/local/lib/node_modules/sweet.js/lib/parser.js:1937:21)
    at throwUnexpected (/usr/local/lib/node_modules/sweet.js/lib/parser.js:1986:9)
    at parsePrimaryExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2347:9)
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2402:61)
    at parsePostfixExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2432:45)
    at parseUnaryExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2483:16)
    at parseBinaryExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2546:16)
    at parseConditionalExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2600:16)
    at parseAssignmentExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2757:16)
    at parseExpression (/usr/local/lib/node_modules/sweet.js/lib/parser.js:2787:16)
```

**Comment by natefaubion** [comment]
No, you cannot just throw any language at it :) sweet.js expects js + macros as input, and gives you plain js as output.

**Comment by IngwiePhoenix** [comment]
Ah okay. Then I just gonna try it another way. :)

**Comment by IngwiePhoenix** [comment]
Turns out that `ojc` also uses an AST parser. Mmh. Looks like I have to return on using my RegExp. But at least I now know how to use sweet.js. :)

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
