### ISSUE TITLE
es6-module branch appears to be broken

### ISSUE THREAD

**Issue by zackp30** [mozilla/sweet.js#472]
```js
operator + 12 left { $base, $exp } => #{ console.log($base) }
```
(should be correct)

causes this:
```
/home/zack/sweet.js/lib/parser.js:1
rs !== "undefined"){program.errors = extra.errors;}}catch(e) {throw e;}finally
                                                                    ^
Error: Line 1: Unexpected identifier
[... operator + 12 left { $base ...]
    at throwError (/home/zack/sweet.js/lib/parser.js:1:39951)
    at throwUnexpected (/home/zack/sweet.js/lib/parser.js:1:40770)
    at consumeSemicolon (/home/zack/sweet.js/lib/parser.js:1:42348)
    at parseStatement (/home/zack/sweet.js/lib/parser.js:1:79246)
    at parseSourceElement (/home/zack/sweet.js/lib/parser.js:1:90020)
    at parseProgramElement (/home/zack/sweet.js/lib/parser.js:1:90294)
    at parseProgramElements (/home/zack/sweet.js/lib/parser.js:1:90916)
    at parseProgram (/home/zack/sweet.js/lib/parser.js:1:91587)
    at Object.parse (/home/zack/sweet.js/lib/parser.js:1:109193)
    at /home/zack/sweet.js/lib/sweet.js:109:26
```
when running with:

```
 ./bin/sjs --to-es5=true ~/ohno/src/ohno.js
```

**Comment by zackp30** [comment]
Branch seems to be outdated, closing. (This issue was fixed on IRC)
