### ISSUE TITLE
Is makeRegex actually supported?

### ISSUE THREAD

**Issue by curiousdannii** [mozilla/sweet.js#504]
This code gives an error:
```
macro test
{
    case { _ } => {
        letstx $test = [makeRegex( 'test', '', null )];
        return #{ $test };
    }
}
```

```
Error: ASSERT: not implemented
    at assert (/home/dannii/reversify/node_modules/sweet.js/lib/syntax.js:17:19)
    at step (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:1618:21)
    at step (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:1543:32)
    at step (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:1543:32)
    at enforest (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:1654:16)
    at expandToTermTree (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:1980:17)
    at expand (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:2333:21)
    at expandTermTreeToFinal (/home/dannii/reversify/node_modules/sweet.js/lib/expander.js:2168:43)
    at /home/dannii/reversify/node_modules/sweet.js/lib/expander.js:2301:34
    at Array.map (native)
```

Passing a regexp object to makeValue() also doesn't work (which is how it is documented, but would be nice if it did.)

**Comment by disnet** [comment]
Silly bug, wrong token type for regular expressions. Should work now.
