### ISSUE TITLE
Output error with cli tool

### ISSUE THREAD

**Issue by kosmosR2** [mozilla/sweet.js#524]
If I use `sjs script.sjs -o output.js` or `sjs script.sjs --out-file output.js`
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at /whatever/node_modules/sweet.js/bin/sjs:40:8
    at Array.forEach (native)
    at Object.<anonymous> (/whatever/node_modules/sweet.js/bin/sjs:27:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

**Comment by disnet** [comment]
Closed with #525.
